### PR TITLE
feat: add typed module loader

### PR DESCRIPTION
**Pull request by sno2**
This allows for much better integration if someone wants to define types in their own module for python modules.  Also, it stops people from making modules that simply wrap the functions/classes using `deno_python` which would incur in a possible performance deficit which can be bypassed by defining the types at compile-time.

### CODE REVIEW

**Comment by DjDeveloperr** [comment]
The idea LGTM. However, I think we could have a better API for that, wrapping `Python` in additional `PythonLoader` class seems a bit unnecessary. Preferably, something in `Python` interface itself would be better.

**Comment by sno2** [comment]
Yeah, I didn't want to have to create another class either.  However, the `Python` class is eagerly constructed which makes having generics on the main class itself impossible.  I've moved the loader to a method, how does that look?

**Comment by DjDeveloperr** [comment]
So I just experimented with some generic & `declare` magic. We can do something like this:
```ts
// Base type in our core `deno_python` module
declare global {
  interface PythonModule {
    [name: string]: any;
  }

  // deno-lint-ignore no-empty-interface
  interface PythonModules extends Record<string, PythonModule> {}
}

// Change `import` definition as follows
import<Module extends string>(name: Module): PythonModules[Module]

// Extending those types in `deno_python_types` or similar
declare global {
  interface PythonModules {
    builtins: {
      bool: CallableFunction;
      // etc
    };
  }
}
```

This allows adding strong types for Python Modules into `import` function itself, falling back to `any` in case its not defined.
What do you think?

**Comment by sno2** [comment]
> This allows adding strong types for Python Modules into `import` function itself, falling back to `any` in case its not defined. What do you think?

I don't think that's how `declare global` works.  When you do `declare global`, the changes only show in the current module and other modules that use triple-slash references like the following:

```ts
/// <reference types="foo.d.ts" />
```

Therefore, you can't modify the type of `PythonModules` because the module that defines it itself would need to have the triple-slash reference to the third-party type overrides.

**Comment by sno2** [comment]
FYI we could also augment the `PyObject` into any of our modules using a helper shadow type:

```ts
// dummy impl
type PyObject = { __pyobj: true };

type ShadowPyObject<T> = T extends (...args: any[]) => any
  ? (...params: Parameters<T>) => ShadowPyObject<ReturnType<T>>
  : { [K in keyof T]: ShadowPyObject<T[K]> } & PyObject;

type PyModule<T> = { [K in keyof T]: ShadowPyObject<T[K]> };


declare namespace __NumPy__ {
  export {};

  export const foo: number;

  export function add(a: number, b: number): number;
  export const person: { name: string; age: number; };
}

export type NumPy = PyModule<typeof __NumPy__>;

const np: NumPy = null!;
np.foo.__pyobj // access 'PyObject' stuff
np.foo + 2 // act like regular type

// return types as well
np.add(2, 3).__pyobj
np.add(2, 3) + 5

// and nested objects
np.person.__pyobj;
np.person.age.__pyobj;
```

[TypeScript Playground](https://www.typescriptlang.org/play?#code/PTAEBMFcFtoT1AS2gBwDYFgBQAXOKBTUABTgHkAjAKwIGMdQBeUAb1AH12U4B7agLlA4ATpCIBfANzZseQqADKACwCG4HgHdSlGvQA8AFQB8TUAdAEAHjgIA7cAGdQACgB07lcIDmDwSttwANoAugCUTCb+cNigoAD8Lu6uKJ4q0L4kqdAENsIOhkbhjCbKapra1HQ4egBKOZDCtgb4BAVGMaCCbIEA0ki2oADWBLwAZmbBgqXqWuSV+ga9wSbioABkJHO6ONJYsi2bALI8UGitxqbdfYgDw2MTU6ozFduGSyu7MljgdGieRLY0gQHClaEROAA5GCkTisDpWFA8YQMFhSL6xBFIhi0Hi2BwMUY8HiCWwwCgEYSfLAYyyI5GgUaQWz0RC40BqcDOFQkskUgA0oAoPOg5OEoWFot2NLp2Nx+NAhDyuK6oEB2UE+OENy8knZXgIEopurRWHEX0x9LkRCh0FIplIx1OrStPHGkOhcE4RipOLxDFsKEENrtzFJaDQAEJdgHXISeK5ONw+FRQCB2bQwQ4nAByF5VbOgfGQUajbAxuOgADUoAATKmwCp6KA0IhhqBhAQvJA-sIhC0vmmOzgGgMrU4VE4NARw2WUK4Oc4awKAMyhBNcXjUWfz8CcpegVdV0AAVgHDfsquBNnAoGTVQc28VDlx66T1Gjc6fL5U+tfm6okhAA)

**Comment by DjDeveloperr** [comment]
Oh right, should've tested it first. Anyways, it is possible to make `Python` constructible more than once, we just need to move initialize FFI call out of the constructor. Could we have a generic parameter there instead?

**Comment by DjDeveloperr** [comment]
@sno2 Any update on this PR?

**Comment by DjDeveloperr** [comment]
I'll close as stale for now. Feel free to reopen or post any updates.

**Pull request closed without merging**
